# Generated by Django 5.1.2 on 2024-10-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_document_key_alter_document_encrypted_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='key',
            new_name='encryption_key',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='encrypted_file',
            field=models.FileField(upload_to='encrypted_documents/'),
        ),
    ]
